export const SET_FORM_DATA = 'SET_FORM_DATA';
export const LOAD_PENDING = "LOAD_PENDING";

export const SET_MANAGED_USER = 'SET_MANAGED_USER';

export const SET_USER_INFORMATION = 'SET_USER_INFORMATION';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = "LOG_OUT";
export const REGISTER = "REGISTER";

export const GET_ALL_USERS = "GET_ALL_USERS";

export const ERROR = "ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const PURGE = "PURGE";

export const GET_PRESET_DATA = "GET_PRESET_DATA";
export const UPDATE_PRESET_DATA = "UPDATE_PRESET_DATA";
export const DELETE_VALUE = "DELETE_VALUE";

export const GET_PENDING_OBSERVATIONS = "GET_PENDING_OBSERVATIONS";
export const GET_PENDING_OBSERVATION = "GET_PENDING_OBSERVATION";
export const GET_PENDING_OBSERVATION_COUNT = "GET_PENDING_OBSERVATION_COUNT";
